// ExportPDFButton.jsx
export default function ExportPDFButton({ city, startDate, endDate, itinerary = [] }) {

    const byDay = itinerary.reduce((acc, item) => {
        const d = item.day ?? 1;
        if (!acc[d]) acc[d] = [];
        acc[d].push(item);
        return acc;
    }, {});

    const dayKeys = Object.keys(byDay).map(Number).sort((a, b) => a - b);

    const CAT_ICONS = {
        food: "🍽️", museums: "🏛️", nature: "🌿", shopping: "🛍️",
        nightlife: "🌙", landmarks: "🏙️", adventure: "⛰️",
    };

    const handleExport = () => {
        const win = window.open("", "_blank");

        const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${city || "My Trip"} – TripWise Itinerary</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      background: white;
      color: #111;
      padding: 36px 40px;
      max-width: 860px;
      margin: 0 auto;
    }

    .header {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      border-bottom: 3px solid #6366f1;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .header-title {
      font-size: 28px;
      font-weight: 800;
      color: #111;
      letter-spacing: -0.03em;
    }
    .header-sub {
      font-size: 13px;
      color: #6b7280;
      margin-top: 4px;
    }
    .header-badge {
      background: #6366f1;
      color: white;
      font-size: 12px;
      font-weight: 700;
      padding: 6px 14px;
      border-radius: 99px;
      white-space: nowrap;
    }

    .day-header {
      font-size: 15px;
      font-weight: 800;
      color: #6366f1;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      margin: 28px 0 12px;
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .day-header::after {
      content: '';
      flex: 1;
      height: 1px;
      background: #e5e7eb;
    }

    .place {
      display: flex;
      gap: 14px;
      align-items: flex-start;
      padding: 14px 16px;
      border: 1px solid #e5e7eb;
      border-radius: 14px;
      margin-bottom: 10px;
      page-break-inside: avoid;
      background: #fafafa;
    }
    .place-num {
      width: 30px;
      height: 30px;
      border-radius: 50%;
      background: #6366f1;
      color: white;
      font-size: 13px;
      font-weight: 800;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      margin-top: 2px;
    }
    .place-body { flex: 1; }
    .place-name {
      font-size: 15px;
      font-weight: 700;
      color: #111;
      margin-bottom: 3px;
    }
    .place-address {
      font-size: 12px;
      color: #6b7280;
      margin-bottom: 6px;
    }
    .place-meta {
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
    }
    .pill {
      font-size: 11px;
      padding: 2px 10px;
      border-radius: 99px;
      border: 1px solid #e5e7eb;
      color: #374151;
      background: white;
    }
    .place-time {
      font-size: 13px;
      font-weight: 700;
      color: #6366f1;
      white-space: nowrap;
      margin-top: 2px;
    }

    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 12px;
      color: #9ca3af;
    }

    @page { margin: 16mm; }
  </style>
</head>
<body>

  <div class="header">
    <div>
      <div class="header-title">✈️ ${city || "My Trip"}</div>
      <div class="header-sub">
        ${startDate ? `📅 ${startDate} → ${endDate}` : ""}
        &nbsp;·&nbsp; ${itinerary.length} stops total
      </div>
    </div>
    <div class="header-badge">TripWise Itinerary</div>
  </div>

  ${dayKeys.map(day => `
    <div class="day-header">Day ${day} &nbsp;·&nbsp; ${byDay[day].length} stops</div>
    ${byDay[day].map((place, i) => `
      <div class="place">
        <div class="place-num">${i + 1}</div>
        <div class="place-body">
          <div class="place-name">${CAT_ICONS[place.category] || "📍"} ${place.name || ""}</div>
          ${place.address ? `<div class="place-address">📍 ${place.address}</div>` : ""}
          <div class="place-meta">
            ${place.category ? `<span class="pill">${place.category}</span>` : ""}
            ${place.rating ? `<span class="pill">⭐ ${place.rating}</span>` : ""}
            ${place.walkTime ? `<span class="pill">🚶 ${place.walkTime}</span>` : ""}
            ${place.driveTime ? `<span class="pill">🚗 ${place.driveTime}</span>` : ""}
          </div>
        </div>
        ${place.time ? `<div class="place-time">${place.time}</div>` : ""}
      </div>
    `).join("")}
  `).join("")}

  <div class="footer">
    Generated by TripWise · Have a great trip! 🌍
  </div>

  <script>
    window.onload = () => { window.print(); }
  </script>
</body>
</html>`;

        win.document.write(html);
        win.document.close();
    };

    return (
        <button
            onClick={handleExport}
            style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 6,
                padding: "10px 18px",
                borderRadius: 14,
                background: "rgba(255,255,255,0.15)",
                backdropFilter: "blur(10px)",
                border: "1px solid rgba(255,255,255,0.25)",
                color: "white",
                fontSize: 14,
                fontWeight: 600,
                cursor: "pointer",
                transition: "background 0.2s",
            }}
            onMouseEnter={e => e.currentTarget.style.background = "rgba(255,255,255,0.25)"}
            onMouseLeave={e => e.currentTarget.style.background = "rgba(255,255,255,0.15)"}
        >
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 17V3" /><path d="m6 11 6 6 6-6" />
                <path d="M19 21H5" />
            </svg>
            Save as PDF
        </button>
    );
}